# Config file for automatic testing at travis-ci.org
sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
language: python
python:
  - 3.6
env:
  - PYTHONPATH=$TRAVIS_BUILD_DIR GITHUB_ACCESS_TOKEN=secret PIVOTAL_ACCESS_TOKEN=secret SECRET_KEY=secret
install:
  - pip install pipenv
  - pipenv install --dev --skip-lock
before_script:
  - pipenv run flake8
script:
  - pipenv run py.test
